language: ruby
rvm:
<<<<<<< HEAD
  - 2.7.1
=======
  - 2.6.3

before_install:
  - gem update --system
  - gem install bundler
>>>>>>> upstream/NiR--improve-dockerfile

addons:
  postgresql: "9.6"

services:
  - postgresql
  - redis

before_script:
  - psql -c 'create database "octobox_test";' -U postgres || true

script:
<<<<<<< HEAD
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
=======
  - RAILS_ENV=test bundle exec rake --trace rubocop db:migrate test:skip_visuals
>>>>>>> upstream/NiR--improve-dockerfile

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

<<<<<<< HEAD
=======
env:
  matrix:
    - DATABASE=mysql2
    - DATABASE=postgresql

>>>>>>> upstream/NiR--improve-dockerfile
notifications:
  email: false
