language: ruby
rvm:
  - 2.7.0

addons:
  postgresql: "9.6"

services:
  - postgresql
  - redis

before_script:
  - psql -c 'create database "octobox_test";' -U postgres || true

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

notifications:
  email: false
