language: ruby
rvm:
  - 2.6.0

before_install:
  - gem update --system
  - gem install bundler

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

services:
  - postgresql
  - mysql
  - redis

before_script:
  - psql -c 'create database "octobox_test";' -U postgres || true
  - mysql -u root -e 'create database octobox_test;' || true

script:
  - RAILS_ENV=test bundle exec rake --trace rubocop db:migrate test:skip_visuals

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

env:
  global:
    - PGPORT=5433
  matrix:
    - DATABASE=mysql2
    - DATABASE=postgresql

notifications:
  email: false
