version: '3'
services:
  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
  app:
    image: octoboxio/octobox:latest
    ports:
      - 3000:3000
    links:
      - database:database.service.octobox.internal
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - OCTOBOX_DATABASE_NAME=${OCTOBOX_DATABASE_NAME}
      - OCTOBOX_DATABASE_USER=${OCTOBOX_DATABASE_USER}
      - OCTOBOX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - OCTOBOX_DATABASE_HOST=database.service.octobox.internal
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
    driver: bridge            