version: '3'
services:
  database.service.octobox.internal:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=development
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
  app:
    image: octoboxio/octobox:latest
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - OCTOBOX_DATABASE_NAME=postgres
      - OCTOBOX_DATABASE_USERNAME=postgres
      - OCTOBOX_DATABASE_PASSWORD=development
      - OCTOBOX_DATABASE_HOST=database.service.octobox.internal
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
    driver: bridge
