# ================================================================================
# Template for installing OctoBox on OpenShift
# --------------------------------------------

# Usage:

# Create own OpenShift project:
# $ oc new-project octobox

# Create template:
# $ oc create -f openshift-template.yml

# Instantiate app:
# $ oc new-app octobox \
#    -p ROUTE_HOSTNAME=app-octobox.my.base.cluster.com \
#    -p GITHUB_CLIENT_ID=1234589abcfde \
#    -p GITHUB_CLIENT_SECRET=d84c1502e5565bb3ee4532324324324234

apiVersion: v1
kind: Template
metadata:
  name: octobox
parameters:
- name: GITHUB_CLIENT_ID
  description: GitHub ID of your registered OAuth App
  required: true
- name: GITHUB_CLIENT_SECRET
  description: The GitHub secret for the OAuth App
  required: true
- name: ROUTE_HOSTNAME
  description: The external hostname for accessing octobox
  required: true
- name: VERSION
  description: Version to use. "latest" by default
  value: latest
  required: true
- description: Password for the PostgreSQL connection user.
  displayName: PostgreSQL Connection Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: POSTGRES_PASSWORD
  required: true
- name: MINIMUM_REFRESH_INTERVAL
  value: "5"
  required: true
- name: FETCH_SUBJECT
  value: "true"
  required: true
- name: VERSION
  description: Version to use. "latest" by default
  value: latest
  required: true
message: |
  OctoBox is installed.
  See https://github.com/octobox for configuration and usage instructions.
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: octobox
    name: app
  spec:
    host: ${ROUTE_HOSTNAME}
    path: /
    port:
      targetPort: 3000
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: octobox-backend
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: octobox
    name: octobox-backend
  spec:
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: octobox
      type: backend
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: octobox-backend
    labels:
      app: octobox
      type: backend
  spec:
    tags:
    - from:
        kind: DockerImage
        name: octoboxio/octobox:${VERSION}
      name: ${VERSION}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: octobox-backend
    labels:
      app: octobox
  spec:
    replicas: 1
    selector:
      app: octobox
      type: backend
    template:
      metadata:
        labels:
          app: octobox
          type: backend
      spec:
        containers:
        - name: octobox
          image: ' '
          imagePullPolicy: IfNotPresent
          env:
          - name: RAILS_ENV
            value: development
          - name: GITHUB_CLIENT_ID
            value: ${GITHUB_CLIENT_ID}
          - name: GITHUB_CLIENT_SECRET
            value: ${GITHUB_CLIENT_SECRET}
          - name: OCTOBOX_DATABASE_NAME
            value: postgres
          - name: OCTOBOX_DATABASE_USERNAME
            value: postgres
          - name: OCTOBOX_DATABASE_PASSWORD
            value: ${POSTGRES_PASSWORD}
          - name: OCTOBOX_DATABASE_HOST
            value: octobox-db
          - name: REDIS_URL
            value: octobox-redis
          - name: MINIMUM_REFRESH_INTERVAL
            value: ${MINIMUM_REFRESH_INTERVAL}
          - name: FETCH_SUBJECT
            value: ${FETCH_SUBJECT}
          resources:
            limits:
              memory: 768Mi
            requests:
              memory: 768Mi
          ports:
          - containerPort: 3000
        restartPolicy: Always
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - octobox
        from:
          kind: ImageStreamTag
          name: octobox-backend:${VERSION}
      type: ImageChange
# -----------------------------------------------------------------
# Postgres DB
- apiVersion: v1
  kind: Service
  metadata:
    name: octobox-db
    labels:
      app: octobox
      type: db
  spec:
    ports:
    - name: postgresql
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: octobox
      type: db
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: octobox-db
    labels:
      app: octobox
      type: db
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: octobox-db
    labels:
      app: octobox
      type: db
  spec:
    replicas: 1
    selector:
      app: octobox
      type: db
    template:
      metadata:
        labels:
          app: octobox
          type: db
      spec:
        containers:
        - name: postgres
          image: ' '
          imagePullPolicy: IfNotPresent
          env:
          - name: POSTGRESQL_USER
            value: postgres
          - name: POSTGRESQL_PASSWORD
            value: ${POSTGRES_PASSWORD}
          - name: POSTGRESQL_DATABASE
            value: postgres
          ports:
          - containerPort: 5432
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 5432
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U postgres -q -d postgres -c 'SELECT 1'
            initialDelaySeconds: 5
          resources:
            limits:
              memory: 255Mi
            requests:
              memory: 255Mi
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: octobox-db-data
        volumes:
        - name: octobox-db-data
          persistentVolumeClaim:
            claimName: octobox-db
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - postgres
        from:
          kind: ImageStreamTag
          name: postgresql:9.5
          namespace: openshift
      type: ImageChange

# -----------------------------------------------------------------
# Redis
- apiVersion: v1
  kind: Service
  metadata:
    name: octobox-redis
    labels:
      app: octobox
      type: redis
  spec:
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: octobox
      type: redis
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: octobox-redis
    labels:
      app: octobox
      type: redis
  spec:
    replicas: 1
    selector:
      app: octobox
      type: redis
    template:
      metadata:
        labels:
          app: octobox
          type: redis
      spec:
        containers:
        - name: octobox-redis
          image: redis:3.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 6379
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              host: localhost
              port: 6379
          resources:
            limits:
              memory: 255Mi
            requests:
              memory: 255Mi
    triggers:
    - type: ConfigChange
